[general]
excluded_routes=192.168.0.0/16, 172.16.0.0/12, 100.64.0.0/10, 10.0.0.0/8
geo_location_checker=https://raw.githubusercontent.com/thuhollow2/qure/main/Other/IP_API.js
network_check_url=http://www.baidu.com/
server_check_url=http://www.gstatic.com/generate_204

[dns]
server=119.29.29.29
server=223.5.5.5
server=1.0.0.1
server=8.8.8.8

[policy]
static=🚀 节点组选择, ♻️ 所有节点-自动, 🚀 所有节点-手动-1, 🚀 所有节点-手动-2, ♻️ IPv6节点-自动, 🚀 IPv6节点-手动, DIRECT, REJECT
url-latency-benchmark=♻️ 所有节点-自动, 🇨🇳CN-101.42.30.206-80, 🇨🇳CN-111.230.252.149-50002, 🇨🇳CN-111.67.201.33-10000, 🇨🇳CN-112.132.212.112-50002, 🇨🇳CN-113.121.40.50-5658, 🇨🇳CN-123.207.75.74-80, 🇨🇳CN-123.249.101.15-19709, 🇨🇳CN-36.150.27.31-80, 🇨🇳CN-39.103.165.178-56002, 🇨🇳CN-60.190.195.146-10800, 🇨🇳CN-61.153.42.218-7302, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Auto.png
static=🚀 所有节点-手动-1, 本文件创建时间：Mon Aug  7 13:16:28 UTC 2023, 🇨🇳CN-101.42.30.206-80, 🇨🇳CN-111.230.252.149-50002, 🇨🇳CN-111.67.201.33-10000, 🇨🇳CN-112.132.212.112-50002, 🇨🇳CN-113.121.40.50-5658, 🇨🇳CN-123.207.75.74-80, 🇨🇳CN-123.249.101.15-19709, 🇨🇳CN-36.150.27.31-80, 🇨🇳CN-39.103.165.178-56002, 🇨🇳CN-60.190.195.146-10800, 🇨🇳CN-61.153.42.218-7302, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Proxy.png
static=🚀 所有节点-手动-2, 本文件创建时间：Mon Aug  7 13:16:28 UTC 2023, 🇨🇳CN-101.42.30.206-80, 🇨🇳CN-111.230.252.149-50002, 🇨🇳CN-111.67.201.33-10000, 🇨🇳CN-112.132.212.112-50002, 🇨🇳CN-113.121.40.50-5658, 🇨🇳CN-123.207.75.74-80, 🇨🇳CN-123.249.101.15-19709, 🇨🇳CN-36.150.27.31-80, 🇨🇳CN-39.103.165.178-56002, 🇨🇳CN-60.190.195.146-10800, 🇨🇳CN-61.153.42.218-7302, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Proxy.png
static=♻️ IPv6节点-自动, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Auto.png
static=🚀 IPv6节点-手动, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Proxy.png
static=🌏 国内媒体, 🚀 节点组选择, ♻️ 所有节点-自动, 🚀 所有节点-手动-1, 🚀 所有节点-手动-2, ♻️ IPv6节点-自动, 🚀 IPv6节点-手动, DIRECT, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Media.png
static=🎯 国内网站, 🚀 节点组选择, ♻️ 所有节点-自动, 🚀 所有节点-手动-1, 🚀 所有节点-手动-2, ♻️ IPv6节点-自动, 🚀 IPv6节点-手动, DIRECT, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Direct.png
static=🐟 其他网站, DIRECT, 🚀 节点组选择, ♻️ 所有节点-自动, 🚀 所有节点-手动-1, 🚀 所有节点-手动-2, ♻️ IPv6节点-自动, 🚀 IPv6节点-手动, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Final.png

[server_remote]

[filter_remote]
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/ChinaMedia.list, tag=🌏 国内媒体, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/ChinaIPv4.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/ChinaIPv6.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/ChinaDomain.list, tag=🎯 国内网站, enabled=true

[rewrite_remote]

[server_local]
vmess = 255.255.255.255:10086, method=chacha20-ietf-poly1305, password=00000000-0000-0000-0000-000000000000, aead=true, fast-open=false, udp-relay=true, tag=本文件创建时间：Mon Aug  7 13:16:28 UTC 2023
vmess = 101.42.30.206:80, method=chacha20-ietf-poly1305, password=24bc9855-8f7c-4543-e29d-970045f205f2, aead=true, obfs=ws, obfs-host=, obfs-uri=/, fast-open=false, udp-relay=true, tag=🇨🇳CN-101.42.30.206-80
vmess = 111.230.252.149:50002, method=chacha20-ietf-poly1305, password=418048af-a293-4b99-9b0c-98ca3580dd24, aead=false, fast-open=false, udp-relay=true, tag=🇨🇳CN-111.230.252.149-50002
vmess = jiangxi4.209966.xyz:10000, method=chacha20-ietf-poly1305, password=3097c8db-70a5-4b3f-a54d-54685a00d086, aead=true, obfs=ws, obfs-host=tms.dingtalk.com, obfs-uri=/neimenggu001, fast-open=false, udp-relay=true, tag=🇨🇳CN-111.67.201.33-10000
vmess = 112.132.212.112:50002, method=chacha20-ietf-poly1305, password=418048af-a293-4b99-9b0c-98ca3580dd24, aead=false, fast-open=false, udp-relay=true, tag=🇨🇳CN-112.132.212.112-50002
socks5 = 113.121.40.50:5658, fast-open=false, udp-relay=true, tag=🇨🇳CN-113.121.40.50-5658
vmess = 123.207.75.74:80, method=chacha20-ietf-poly1305, password=e2b73315-2fc1-4e86-8df3-023baf466438, aead=true, obfs=ws, obfs-host=, obfs-uri=/, fast-open=false, udp-relay=true, tag=🇨🇳CN-123.207.75.74-80
vmess = sc.jeidian.xyz:80, method=chacha20-ietf-poly1305, password=cc7484da-6041-4bcc-bc66-2b41e7896a6f, aead=true, obfs=ws, obfs-host=tms.dingtalk.com, obfs-uri=/, fast-open=false, udp-relay=true, tag=🇨🇳CN-123.249.101.15-19709
socks5 = 61.153.42.218:7302, fast-open=false, udp-relay=true, tag=🇨🇳CN-36.150.27.31-80
vmess = 14.29.191.228:46794, method=chacha20-ietf-poly1305, password=ffe242ca-10d6-4d61-bbd4-9aed3e25d132, aead=true, obfs=ws, obfs-host=tms.dingtalk.com, obfs-uri=/, fast-open=false, udp-relay=true, tag=🇨🇳CN-39.103.165.178-56002
socks5 = 39.170.85.129:7302, fast-open=false, udp-relay=true, tag=🇨🇳CN-60.190.195.146-10800
vmess = zj.wutao7.top:80, method=chacha20-ietf-poly1305, password=cc7484da-6041-4bcc-bc66-2b41e7896a6f, aead=true, obfs=ws, obfs-host=tms.dingtalk.com, obfs-uri=/, fast-open=false, udp-relay=true, tag=🇨🇳CN-61.153.42.218-7302

[filter_local]
GEOIP,CN,🎯 国内网站
FINAL,🐟 其他网站

[rewrite_local]

[mitm]

