[general]
excluded_routes=192.168.0.0/16, 172.16.0.0/12, 100.64.0.0/10, 10.0.0.0/8
geo_location_checker=https://raw.githubusercontent.com/thuhollow2/qure/main/Other/IP_API.js
network_check_url=http://www.baidu.com/
server_check_url=http://www.gstatic.com/generate_204

[dns]
server=119.29.29.29
server=223.5.5.5
server=1.0.0.1
server=8.8.8.8

[policy]
static=🚀 节点组选择, ♻️ 所有节点-自动, 🚀 所有节点-手动-1, 🚀 所有节点-手动-2, ♻️ IPv6节点-自动, 🚀 IPv6节点-手动, DIRECT, REJECT
url-latency-benchmark=♻️ 所有节点-自动, 本文件创建时间：Fri Jul 14 17:38:38 UTC 2023, 🇨🇳CN-123.126.158.50-80, 🇨🇳CN-123.249.101.15-19709, 🇨🇳CN-183.221.242.103-9443, 🇨🇳CN-42.192.17.34-50002, 🇨🇳CN-47.104.240.230-50002, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Auto.png
static=🚀 所有节点-手动-1, 本文件创建时间：Fri Jul 14 17:38:38 UTC 2023, 🇨🇳CN-123.126.158.50-80, 🇨🇳CN-123.249.101.15-19709, 🇨🇳CN-183.221.242.103-9443, 🇨🇳CN-42.192.17.34-50002, 🇨🇳CN-47.104.240.230-50002, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Proxy.png
static=🚀 所有节点-手动-2, 本文件创建时间：Fri Jul 14 17:38:38 UTC 2023, 🇨🇳CN-123.126.158.50-80, 🇨🇳CN-123.249.101.15-19709, 🇨🇳CN-183.221.242.103-9443, 🇨🇳CN-42.192.17.34-50002, 🇨🇳CN-47.104.240.230-50002, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Proxy.png
static=♻️ IPv6节点-自动, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Auto.png
static=🚀 IPv6节点-手动, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Proxy.png
static=🌏 国内媒体, 🚀 节点组选择, ♻️ 所有节点-自动, 🚀 所有节点-手动-1, 🚀 所有节点-手动-2, ♻️ IPv6节点-自动, 🚀 IPv6节点-手动, DIRECT, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Media.png
static=🎯 国内网站, 🚀 节点组选择, ♻️ 所有节点-自动, 🚀 所有节点-手动-1, 🚀 所有节点-手动-2, ♻️ IPv6节点-自动, 🚀 IPv6节点-手动, DIRECT, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Direct.png
static=🐟 其他网站, DIRECT, 🚀 节点组选择, ♻️ 所有节点-自动, 🚀 所有节点-手动-1, 🚀 所有节点-手动-2, ♻️ IPv6节点-自动, 🚀 IPv6节点-手动, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Final.png

[server_remote]

[filter_remote]
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/ChinaMedia.list, tag=🌏 国内媒体, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/ChinaIPv4.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/ChinaIPv6.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/ChinaDomain.list, tag=🎯 国内网站, enabled=true

[rewrite_remote]

[server_local]
vmess = 255.255.255.255:10086, method=chacha20-ietf-poly1305, password=00000000-0000-0000-0000-000000000000, aead=true, fast-open=false, udp-relay=true, tag=本文件创建时间：Fri Jul 14 17:38:38 UTC 2023
http = 101.91.147.77:7890, username=none, password=none, over-tls=false, fast-open=false, udp-relay=true, tag=🇨🇳CN-123.126.158.50-80
trojan = w12.udpgw.com:443, password=08964210-e7b8-11ec-95aa-1239d0255272, over-tls=false, fast-open=false, udp-relay=true, tag=🇨🇳CN-123.249.101.15-19709
http = 183.221.242.103:9443, username=none, password=none, over-tls=false, fast-open=false, udp-relay=true, tag=🇨🇳CN-183.221.242.103-9443
trojan = hk2.yihaobao.xyz:10023, password=eeeebdd2-5aa5-4325-b69f-5b8b2c16d9a0, over-tls=false, fast-open=false, udp-relay=true, tag=🇨🇳CN-42.192.17.34-50002
trojan = fscsg.fscloud123456789.com:443, password=7fb75604-9656-4c30-8662-6533c580e794, over-tls=false, fast-open=false, udp-relay=true, tag=🇨🇳CN-47.104.240.230-50002

[filter_local]
GEOIP,CN,🎯 国内网站
FINAL,🐟 其他网站

[rewrite_local]

[mitm]

