[general]
excluded_routes=192.168.0.0/16, 172.16.0.0/12, 100.64.0.0/10, 10.0.0.0/8
geo_location_checker=https://raw.githubusercontent.com/thuhollow2/qure/main/Other/IP_API.js
network_check_url=http://www.baidu.com/
server_check_url=http://www.gstatic.com/generate_204

[dns]
server=119.29.29.29
server=223.5.5.5
server=1.0.0.1
server=8.8.8.8

[policy]
url-latency-benchmark=♻️ 自动选择, 本文件创建时间：Sun May 28 01:01:15 UTC 2023, 🇨🇳CN-101.32.201.222-443, 🇨🇳CN-112.132.215.189-50002, 🇨🇳CN-118.140.27.231-443, 🇨🇳CN-123.249.101.15-19709, 🇨🇳CN-36.133.171.209-11023, 🇨🇳CN-36.134.16.171-11023, 🇨🇳CN-36.134.16.190-11023, 🇨🇳CN-47.93.231.218-53022, 🇨🇳CN-59.124.94.151-8443, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Auto.png
static=🚀 手动切换-1, 本文件创建时间：Sun May 28 01:01:15 UTC 2023, 🇨🇳CN-101.32.201.222-443, 🇨🇳CN-112.132.215.189-50002, 🇨🇳CN-118.140.27.231-443, 🇨🇳CN-123.249.101.15-19709, 🇨🇳CN-36.133.171.209-11023, 🇨🇳CN-36.134.16.171-11023, 🇨🇳CN-36.134.16.190-11023, 🇨🇳CN-47.93.231.218-53022, 🇨🇳CN-59.124.94.151-8443
static=🚀 手动切换-2, 本文件创建时间：Sun May 28 01:01:15 UTC 2023, 🇨🇳CN-101.32.201.222-443, 🇨🇳CN-112.132.215.189-50002, 🇨🇳CN-118.140.27.231-443, 🇨🇳CN-123.249.101.15-19709, 🇨🇳CN-36.133.171.209-11023, 🇨🇳CN-36.134.16.171-11023, 🇨🇳CN-36.134.16.190-11023, 🇨🇳CN-47.93.231.218-53022, 🇨🇳CN-59.124.94.151-8443
static=♻️ IPv6-自动, DIRECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Auto.png
static=🚀 IPv6-手动, DIRECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Proxy.png
static=🛑 广告拦截, DIRECT, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Advertising.png
static=🌏 国内媒体, ♻️ 自动选择, 🚀 手动切换-1, 🚀 手动切换-2, ♻️ IPv6-自动, 🚀 IPv6-手动, DIRECT, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Media.png
static=🎯 国内网站, ♻️ 自动选择, 🚀 手动切换-1, 🚀 手动切换-2, ♻️ IPv6-自动, 🚀 IPv6-手动, DIRECT, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Direct.png
static=🐟 其他网站, DIRECT, ♻️ 自动选择, 🚀 手动切换-1, 🚀 手动切换-2, ♻️ IPv6-自动, 🚀 IPv6-手动, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Final.png

[server_remote]

[filter_remote]
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/BanAD.list, tag=🛑 广告拦截, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/BanProgramAD.list, tag=🛑 广告拦截, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/ChinaMedia.list, tag=🌏 国内媒体, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/UnBan.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/ChinaDomain.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/ChinaCompanyIp.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/ChinaIp.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/ChinaIpV6.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/GoogleCN.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/SteamCN.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/Download.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/Direct.list, tag=🎯 国内网站, enabled=true

[rewrite_remote]

[server_local]
vmess = 255.255.255.255:10086, method=chacha20-ietf-poly1305, password=00000000-0000-0000-0000-000000000000, aead=true, fast-open=false, udp-relay=true, tag=本文件创建时间：Sun May 28 01:01:15 UTC 2023
vmess = hk.biutefor.icu:443, method=chacha20-ietf-poly1305, password=71b2655e-07d9-4dad-a770-a2b08275142b, aead=true, tls13=false, obfs=wss, obfs-host=hk.biutefor.icu, obfs-uri=/biutefor.icu, fast-open=false, udp-relay=true, tls-verification=false, tag=🇨🇳CN-101.32.201.222-443
vmess = 112.132.215.189:50002, method=chacha20-ietf-poly1305, password=418048af-a293-4b99-9b0c-98ca3580dd24, aead=false, fast-open=false, udp-relay=true, tag=🇨🇳CN-112.132.215.189-50002
vmess = hgc1.pmssr.xyz:443, method=chacha20-ietf-poly1305, password=95b2dc83-a476-4a82-93b2-0d77b4c30c18, aead=true, tls13=false, obfs=wss, obfs-host=hgc1.pmssr.xyz, obfs-uri=/sometimesnaive, fast-open=false, udp-relay=true, tls-verification=false, tag=🇨🇳CN-118.140.27.231-443
vmess = 123.249.101.15:19709, method=chacha20-ietf-poly1305, password=2f278a45-940a-46c1-c886-77f3b2d33987, aead=true, obfs=ws, obfs-host=, obfs-uri=/, fast-open=false, udp-relay=true, tag=🇨🇳CN-123.249.101.15-19709
vmess = 36.133.171.209:11023, method=chacha20-ietf-poly1305, password=8c042a38-71c1-1dcb-00df-54880236e0dc, aead=true, fast-open=false, udp-relay=true, tag=🇨🇳CN-36.133.171.209-11023
vmess = 36.134.16.171:11023, method=chacha20-ietf-poly1305, password=8c042a38-71c1-1dcb-00df-54880236e0dc, aead=true, fast-open=false, udp-relay=true, tag=🇨🇳CN-36.134.16.171-11023
vmess = 36.134.16.190:11023, method=chacha20-ietf-poly1305, password=8c042a38-71c1-1dcb-00df-54880236e0dc, aead=true, fast-open=false, udp-relay=true, tag=🇨🇳CN-36.134.16.190-11023
vmess = 47.93.231.218:53022, method=chacha20-ietf-poly1305, password=95fd7642-2160-4528-e909-3d526b533013, aead=true, obfs=ws, obfs-host=, obfs-uri=/, fast-open=false, udp-relay=true, tag=🇨🇳CN-47.93.231.218-53022
trojan = official.taipeicitygovernment.kiev.ua:8443, password=5505f6ba-cd37-30ce-8f92-be4120c83d7f, over-tls=false, fast-open=false, udp-relay=true, tag=🇨🇳CN-59.124.94.151-8443

[filter_local]
GEOIP,CN,🎯 国内网站
FINAL,🐟 其他网站

[rewrite_local]

[mitm]

