[General]
allow-udp-proxy=false
bypass-tun=10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.18.0.0/15,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32
dns-server=system,119.29.29.29,223.5.5.5
host=127.0.0.1
skip-proxy=192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,e.crashlynatics.com

[Proxy]
本文件创建时间：Tue May 23 04:26:15 UTC 2023 = vmess,255.255.255.255,10086,chacha20-ietf-poly1305,"00000000-0000-0000-0000-000000000000",over-tls:false,transport:tcp,skip-cert-verify:1
🇨🇳CN-112.132.215.189-50002 = vmess,112.132.215.189,50002,chacha20-ietf-poly1305,"418048af-a293-4b99-9b0c-98ca3580dd24",over-tls:false,transport:tcp,skip-cert-verify:1
🇨🇳CN-202.79.172.27-443 = trojan,165.154.226.87,443,ca7febc2-bb45-4e6d-810e-ab0af6009c4e,skip-cert-verify:1

[Remote Proxy]

[Proxy Group]
♻️ 自动选择 = url-test,本文件创建时间：Tue May 23 04:26:15 UTC 2023,🇨🇳CN-112.132.215.189-50002,🇨🇳CN-202.79.172.27-443,url=http://www.gstatic.com/generate_204,interval=300
🚀 手动切换-1 = select,本文件创建时间：Tue May 23 04:26:15 UTC 2023,🇨🇳CN-112.132.215.189-50002,🇨🇳CN-202.79.172.27-443
🚀 手动切换-2 = select,本文件创建时间：Tue May 23 04:26:15 UTC 2023,🇨🇳CN-112.132.215.189-50002,🇨🇳CN-202.79.172.27-443
♻️ IPv6-自动 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🚀 IPv6-手动 = select,DIRECT
🛑 广告拦截 = select,DIRECT,REJECT
🌏 国内媒体 = select,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,♻️ IPv6-自动,🚀 IPv6-手动,DIRECT,REJECT
🎯 国内网站 = select,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,♻️ IPv6-自动,🚀 IPv6-手动,DIRECT,REJECT
🐟 其他网站 = select,DIRECT,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,♻️ IPv6-自动,🚀 IPv6-手动,REJECT

[Rule]
GEOIP,CN,🎯 国内网站
FINAL,🐟 其他网站

[Remote Rule]
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/BanAD.list,🛑 广告拦截
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/BanProgramAD.list,🛑 广告拦截
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ChinaMedia.list,🌏 国内媒体
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/UnBan.list,🎯 国内网站
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ChinaDomain.list,🎯 国内网站
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ChinaCompanyIp.list,🎯 国内网站
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ChinaIp.list,🎯 国内网站
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/GoogleCN.list,🎯 国内网站
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/SteamCN.list,🎯 国内网站
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/Download.list,🎯 国内网站
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/Direct.list,🎯 国内网站

[URL Rewrite]
enable=true
^https?:\/\/(www.)?(g|google)\.cn https://www.google.com 302

[Remote Rewrite]
https://raw.githubusercontent.com/thuhollow2/rule/main/Loon/AutoRewrite_Example.list,auto

[MITM]
enable=true
hostname=*.example.com,*.sample.com
skip-server-cert-verify=true

