#!MANAGED-CONFIG https://raw.githubusercontent.com/thuhollow2/cn/main/Surge4/surge4config.yaml interval=86400 strict=false

[General]
loglevel = notify
bypass-system = true
skip-proxy = 127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,100.64.0.0/10,localhost,*.local,e.crashlytics.com,captive.apple.com,::ffff:0:0:0:0/1,::ffff:128:0:0:0/1
#DNS设置或根据自己网络情况进行相应设置
bypass-tun = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
dns-server = 119.29.29.29,223.5.5.5

[Proxy]
DIRECT = direct
本文件创建时间：Tue May 23 23:00:02 UTC 2023 = vmess, 255.255.255.255, 10086, username=00000000-0000-0000-0000-000000000000, tls=false, vmess-aead=true, skip-cert-verify=true, tfo=false, udp-relay=true
🇨🇳CN-112.132.215.189-50002 = vmess, 112.132.215.189, 50002, username=418048af-a293-4b99-9b0c-98ca3580dd24, tls=false, vmess-aead=false, skip-cert-verify=true, tfo=false, udp-relay=true
🇨🇳CN-14.29.124.168-25252 = ss, 14.29.124.168, 25252, encrypt-method=aes-128-cfb, password=QazEdcTgb159@$*, tfo=false, udp-relay=true
🇨🇳CN-202.79.171.146-443 = vmess, 202.79.171.155, 443, username=7f37da61-c734-41b4-a8c2-eccfd6ca48f0, tls=true, vmess-aead=false, tls13=false, ws=true, ws-path=/path/080712342310, sni=202.79.171.155, skip-cert-verify=true, tfo=false, udp-relay=true
🇨🇳CN-36.134.16.96-11023 = vmess, 36.134.16.96, 11023, username=8c042a38-71c1-1dcb-00df-54880236e0dc, tls=false, vmess-aead=true, skip-cert-verify=true, tfo=false, udp-relay=true
♻️ IPv6-自动 = direct
🚀 IPv6-手动 = direct

[Proxy Group]
♻️ 自动选择 = url-test,本文件创建时间：Tue May 23 23:00:02 UTC 2023,🇨🇳CN-112.132.215.189-50002,🇨🇳CN-14.29.124.168-25252,🇨🇳CN-202.79.171.146-443,🇨🇳CN-36.134.16.96-11023,url=http://www.gstatic.com/generate_204,interval=300,tolerance=50
🚀 手动切换-1 = select,本文件创建时间：Tue May 23 23:00:02 UTC 2023,🇨🇳CN-112.132.215.189-50002,🇨🇳CN-14.29.124.168-25252,🇨🇳CN-202.79.171.146-443,🇨🇳CN-36.134.16.96-11023
🚀 手动切换-2 = select,本文件创建时间：Tue May 23 23:00:02 UTC 2023,🇨🇳CN-112.132.215.189-50002,🇨🇳CN-14.29.124.168-25252,🇨🇳CN-202.79.171.146-443,🇨🇳CN-36.134.16.96-11023
🛑 广告拦截 = select,DIRECT,REJECT
🌏 国内媒体 = select,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,♻️ IPv6-自动,🚀 IPv6-手动,DIRECT,REJECT
🎯 国内网站 = select,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,♻️ IPv6-自动,🚀 IPv6-手动,DIRECT,REJECT
🐟 其他网站 = select,DIRECT,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,♻️ IPv6-自动,🚀 IPv6-手动,REJECT

[Rule]
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/BanAD.list,🛑 广告拦截,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/BanProgramAD.list,🛑 广告拦截,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ChinaMedia.list,🌏 国内媒体,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/UnBan.list,🎯 国内网站,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ChinaDomain.list,🎯 国内网站,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ChinaCompanyIp.list,🎯 国内网站,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ChinaIp.list,🎯 国内网站,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/GoogleCN.list,🎯 国内网站,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/SteamCN.list,🎯 国内网站,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/Download.list,🎯 国内网站,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/Direct.list,🎯 国内网站,update-interval=86400
GEOIP,CN,🎯 国内网站
FINAL,🐟 其他网站

