#!MANAGED-CONFIG https://raw.githubusercontent.com/thuhollow2/cn/main/Surge4/surge4config.yaml interval=86400 strict=false

[General]
loglevel = notify
bypass-system = true
skip-proxy = 127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,100.64.0.0/10,localhost,*.local,e.crashlytics.com,captive.apple.com,::ffff:0:0:0:0/1,::ffff:128:0:0:0/1
#DNS设置或根据自己网络情况进行相应设置
bypass-tun = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
dns-server = 119.29.29.29,223.5.5.5

[Proxy]
DIRECT = direct
本文件创建时间：Thu Aug  3 15:37:16 UTC 2023 = vmess, 255.255.255.255, 10086, username=00000000-0000-0000-0000-000000000000, tls=false, vmess-aead=true, skip-cert-verify=true, tfo=false, udp-relay=true
🇨🇳CN-101.42.30.206-80 = vmess, 101.42.30.206, 80, username=24bc9855-8f7c-4543-e29d-970045f205f2, tls=false, vmess-aead=true, ws=true, ws-path=/, sni=101.42.30.206, ws-headers=Host:tms.dingtalk.com, skip-cert-verify=true, tfo=false, udp-relay=true
🇨🇳CN-111.178.11.20-8088 = http, 183.221.242.107, 9443, tls=false, skip-cert-verify=true, tfo=false, udp-relay=true
♻️ IPv6节点-自动 = reject
🚀 IPv6节点-手动 = reject

[Proxy Group]
🚀 节点组选择 = select,♻️ 所有节点-自动,🚀 所有节点-手动-1,🚀 所有节点-手动-2,♻️ IPv6节点-自动,🚀 IPv6节点-手动,DIRECT,REJECT
♻️ 所有节点-自动 = url-test,🇨🇳CN-101.42.30.206-80,🇨🇳CN-111.178.11.20-8088,url=http://www.apple.com/library/test/success.html,interval=300,tolerance=50
🚀 所有节点-手动-1 = select,本文件创建时间：Thu Aug  3 15:37:16 UTC 2023,🇨🇳CN-101.42.30.206-80,🇨🇳CN-111.178.11.20-8088
🚀 所有节点-手动-2 = select,本文件创建时间：Thu Aug  3 15:37:16 UTC 2023,🇨🇳CN-101.42.30.206-80,🇨🇳CN-111.178.11.20-8088
🌏 国内媒体 = select,🚀 节点组选择,♻️ 所有节点-自动,🚀 所有节点-手动-1,🚀 所有节点-手动-2,♻️ IPv6节点-自动,🚀 IPv6节点-手动,DIRECT,REJECT
🎯 国内网站 = select,🚀 节点组选择,♻️ 所有节点-自动,🚀 所有节点-手动-1,🚀 所有节点-手动-2,♻️ IPv6节点-自动,🚀 IPv6节点-手动,DIRECT,REJECT
🐟 其他网站 = select,DIRECT,🚀 节点组选择,♻️ 所有节点-自动,🚀 所有节点-手动-1,🚀 所有节点-手动-2,♻️ IPv6节点-自动,🚀 IPv6节点-手动,REJECT

[Rule]
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ChinaMedia.list,🌏 国内媒体,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ChinaIPv4.list,🎯 国内网站,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ChinaIPv6.list,🎯 国内网站,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ChinaDomain.list,🎯 国内网站,update-interval=86400
GEOIP,CN,🎯 国内网站
FINAL,🐟 其他网站

